### ISSUE TITLE
dotfiles caching issue

### ISSUE THREAD

**Issue by jmfrancois** [Talend/generator-talend#13]
cc @talend-agonzalez 
```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Trying to copy from a source that does not exist: /home/agonzalez/.cache/node-yeoman-remote-cache/Talend/tools/master/tools-javascript/.editorconfig
    at EditionInterface.exports._copySingle (/home/agonzalez/git-projects/generator-talend/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/home/agonzalez/git-projects/generator-talend/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at jsDotFiles.forEach (/home/agonzalez/git-projects/generator-talend/generators/dotfiles/index.js:42:13)
    at Array.forEach (native)
    at remote (/home/agonzalez/git-projects/generator-talend/generators/dotfiles/index.js:41:15)
    at done (/home/agonzalez/git-projects/generator-talend/node_modules/yeoman-remote/lib/index.js:80:5)
    at /home/agonzalez/git-projects/generator-talend/node_modules/yeoman-remote/lib/index.js:92:7
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by jmfrancois** [comment]
We also have the problem on travis some times (when the tools repository is updated and the structure change

**Comment by jmfrancois** [comment]
So the solution at the moment is to remove the cache folder:

```$ rm -rf ~/.cache/node-yeoman-remote-cache/Talend/tools/```
